id: P5F26B87C
initial_creation_type: ocr
source_metadata:
  volumes:
    9b06c043f6b746139618ca0c3aab5629:
      base_file: v038.txt
      image_group_id: I1PD95883
      title: དེ་བཞིན་གཤེགས་པ་བདུན་གྱི་སྔོན་གྱི་སྨོན་ལམ་གྱི་ཁྱད་པར་རྒྱས་པ།
      total_pages: 1044
      volume_number: 38
